let initialState = {
    "defaults": [
        [
            {
                "code": "// In how many days is the hack?\n// To find the solution, convert the given milliseconds\n// into days.\n\npublic class Challenge1 {\n\tpublic static void main(String[] args) {\n\t\tint millis = 432000000;\n\t\tint seconds = millis / 1000;\n\t\tint minutes = seconds / 60;\n\t\tint hours = minutes / 60;\n\t\tint days = hours / 24;\n\t\tSystem.out.println(days);\n\t}\n}",
                "code_hint": "// In how many days is the hack?\n// To find the solution, convert the given milliseconds\n// into days.\n\npublic class Challenge1 {\n\tpublic static void main(String[] args) {\n\t\tint millis = 432000000;\n\t\tint seconds = millis / ;\n\t\tint minutes = seconds / ;\n\t\tint hours = minutes / ;\n\t\tint days = hours / ;\n\t\tSystem.out.println(days);\n\t}\n}",
                "default_code": "// In how many days is the hack?\n// To find the solution, convert the given milliseconds\n// into days.\n\npublic class Challenge1 {\n\tpublic static void main(String[] args) {\n\n\t}\n}",
            },
            {
                "code": "// What is The Syndicate's bank account code?\n// To find the solution, find the sum of all\n// even numbers less than 12,386.\n\npublic class Challenge2 {\n\tpublic static void main(String[] args) {\n\t\tint num = 12386;\n\t\tint sum = 0;\n\t\tint count = 0;\n\t\twhile (count < num) {\n\t\t\tif (count % 2 == 0) {\n\t\t\t\tsum += count;\n\t\t\t}\n\t\t\tcount++;\n\t\t}\n\t\tSystem.out.println(sum);\n\t}\n}",
                "code_hint": "// What is The Syndicate's bank account code?\n// To find the solution, find the sum of all\n// even numbers less than 12,386.\n\npublic class Challenge2 {\n\tpublic static void main(String[] args) {\n\t\tint num = 12386;\n\t\tint sum = 0;\n\t\tint count = 0;\n\t\t// Create a Loop to find each even number and add it to the sum\n\t\tSystem.out.println(sum);\n\t}\n}",
                "default_code": "// What is The Syndicate's bank account code?\n// To find the solution, find the sum of all\n// even numbers less than 12,386.\n\npublic class Challenge2 {\n\tpublic static void main(String[] args) {\n\n\t}\n}",
            },
            {
                "code": "// The Syndicate is planning insider trading on an exchange in what city?\n// The message can be decoded by taking every\n// fifth letter of the document.\n\npublic class Challenge3 {\n\tpublic static void main(String[] args) {\n\t\tint num = 5;\n\t\tString input = \"GIWTWVQMBEPDQUXCZWUHJWZKAKBSIVFZKDEZRFTXIPEZOCNFYUSJXTRHQFNXKMDMCUIAMOTPUWNGLSUTTQNRAZVOYCPCGMTCPMQSYOMAXBBIJSBWFAETBOCTIPVUXASJZUCOTIPZXCUXBRSMAQOLOTXGJTXBVUMTIQAZHFYZKEPKBCXYYSBCXYXFHBQLZIUMOICQXTUABRGLGFQFRODAYQXTWLUBONCPOITHFAWWRERPCZWDJTQRXTIODOKGRHFAZOOXQQBPTWTNXRDKVZAMFLADHTQUE\";\n\t\tStringBuilder builder = new StringBuilder();\n\t\tfor (int i = num - 1; i < input.length(); i += num) {\n\t\t\tif (input.charAt(i) == 'X') {\n\t\t\t\tbuilder.append(' ');\n\t\t\t} else {\n\t\t\t\tbuilder.append(input.charAt(i));\n\t\t\t}\n\t\t}\n\t\tSystem.out.println( builder.toString() );\n\t}\n}",
                "code_hint": "// The Syndicate is planning insider trading on an exchange in what city?\n// The message can be decoded by taking every\n// fifth letter of the document.\n\npublic class Challenge3 {\n\tpublic static void main(String[] args) {\n\t\tint num = 5;\n\t\tString input = \"GIWTWVQMBEPDQUXCZWUHJWZKAKBSIVFZKDEZRFTXIPEZOCNFYUSJXTRHQFNXKMDMCUIAMOTPUWNGLSUTTQNRAZVOYCPCGMTCPMQSYOMAXBBIJSBWFAETBOCTIPVUXASJZUCOTIPZXCUXBRSMAQOLOTXGJTXBVUMTIQAZHFYZKEPKBCXYYSBCXYXFHBQLZIUMOICQXTUABRGLGFQFRODAYQXTWLUBONCPOITHFAWWRERPCZWDJTQRXTIODOKGRHFAZOOXQQBPTWTNXRDKVZAMFLADHTQUE\";\n\t\tStringBuilder builder = new StringBuilder();\n\n\t\tSystem.out.println( builder.toString() );\n\t}\n}",
                "default_code": "// The Syndicate is planning insider trading on an exchange in what city?\n// The message can be decoded by taking every\n// fifth letter of the document.\n\npublic class Challenge3 {\n\tpublic static void main(String[] args) {\n\t\tint num = 5;\n\t\tString input = \"GIWTWVQMBEPDQUXCZWUHJWZKAKBSIVFZKDEZRFTXIPEZOCNFYUSJXTRHQFNXKMDMCUIAMOTPUWNGLSUTTQNRAZVOYCPCGMTCPMQSYOMAXBBIJSBWFAETBOCTIPVUXASJZUCOTIPZXCUXBRSMAQOLOTXGJTXBVUMTIQAZHFYZKEPKBCXYYSBCXYXFHBQLZIUMOICQXTUABRGLGFQFRODAYQXTWLUBONCPOITHFAWWRERPCZWDJTQRXTIODOKGRHFAZOOXQQBPTWTNXRDKVZAMFLADHTQUE\";\n\n\t}\n}",
            },
            {
                "code": "// What is the financial publication The Syndicate is trying to hack?\n// To decode a 5-rail cipher like this, put the code in a matrix with a\n// length of 5 (5 rows). Then read the code from top to bottom, left to right\n\npublic class Challenge4 {\n\tpublic static void main(String[] args) {\n\t\tString cipherText = \"TLSHTIIIHA_AHNAMENTCEALE__OK_N_SPI__FCT.\";\n\t\tint rows = 5;\n\t\tint columns = cipherText.length() / rows;\n\t\tchar[][] matrix = new char[rows][columns];\n\t\tint textIdx = 0;\n\n\t\tfor (int row = 0; row < matrix.length; row++) {\n\t\t\tfor ( int col = 0; col < matrix[row].length; col++) {\n\t\t\t\tif (textIdx < cipherText.length()) {\n\t\t\t\t\tmatrix[row][col] = cipherText.charAt(textIdx);\n\t\t\t\t} else {\n\t\t\t\t\tmatrix[row][col] = '-';\n\t\t\t\t}\n\t\t\t\ttextIdx++;\n\t\t\t}\n\t\t}\n\n\t\tStringBuilder builder = new StringBuilder();\n\t\tfor (int col = 0; col < matrix[0].length; col++) {\n\t\t\tfor (int row = 0; row < matrix.length; row++) {\n\t\t\t\tbuilder.append(matrix[row][col]);\n\t\t\t}\n\t\t}\n\n\t\tSystem.out.println( builder.toString() );\n\t}\n}\n",
                "code_hint": "// What is the financial publication The Syndicate is trying to hack?\n// To decode a 5-rail cipher like this, put the code in a matrix with a\n// length of 5 (5 rows). Then read the code from top to bottom, left to right\n\npublic class Challenge4 {\n\tpublic static void main(String[] args) {\n\t\tString cipherText = \"TLSHTIIIHA_AHNAMENTCEALE__OK_N_SPI__FCT.\";\n\t\tint rows = 5;\n\t\tint columns = cipherText.length() / rows;\n\t\tchar[][] matrix = new char[rows][columns];\n\t\t// Keep track of the cipherText index\n\t\tint textIdx = 0;\n\n\t\t// We have a matrix with 5 rows and 8 columns\n\t\t// Fill it with the cipherText from left to right\n\t\t// and top to bottom\n\n\t\t// Now read through the matrix down each column\n\t\t// from top to bottom and left to right and build a String\n\t\t// of the characters.\n\n\t}\n}\n",
                "default_code": "// What is the financial publication The Syndicate is trying to hack?\n// To decode a 5-rail cipher like this, put the code in a matrix with a\n// length of 5 (5 rows). Then read the code from top to bottom, left to right\n\npublic class Challenge4 {\n\tpublic static void main(String[] args) {\n\t\tString cipherText = \"TLSHTIIIHA_AHNAMENTCEALE__OK_N_SPI__FCT.\";\n\n\t}\n}\n",
            },
            {
                "code": "// To what country is the Kingpin planning to flee?\n// To find the solution, exclude all the letters in the\n// code that appear more than once.\n\npublic class Challenge5 {\n\tpublic static void main(String[] args) {\n\t\tString code = \"FJPSCYWJQXHGOUYIFVGHTXCJUYZQMPKEOFRLBXGJVANQOHMKBPXUDC\";\n        StringBuilder builder = new StringBuilder();\n\n\t\tfor (int i = 0; i < code.length(); i++){\n\t\t\tif( code.indexOf(code.charAt(i)) == code.lastIndexOf(code.charAt(i))) {\n\t\t\t\tbuilder.append( code.charAt(i) );\n\t\t\t}\n\t\t}\n\n\t\tSystem.out.println( builder.toString() );\n\t}\n}",
                "code_hint": "// To what country is the Kingpin planning to flee?\n// To find the solution, exclude all the letters in the\n// code that appear more than once.\n\npublic class Challenge5 {\n\tpublic static void main(String[] args) {\n\t\tString code = \"FJPSCYWJQXHGOUYIFVGHTXCJUYZQMPKEOFRLBXGJVANQOHMKBPXUDC\";\n\n\t\t// The .indexOf() String method returns the first index of a character\n\t\t// in a String.\n\t\t// The .lastIndexOf() String method returns the last index of a character\n\t\t// in a String.\n\t}\n}\n",
                "default_code": "// To what country is the Kingpin planning to flee?\n// To find the solution, exclude all the letters in the\n// code that appear more than once.\n\npublic class Challenge5 {\n\tpublic static void main(String[] args) {\n\t\tString code = \"FJPSCYWJQXHGOUYIFVGHTXCJUYZQMPKEOFRLBXGJVANQOHMKBPXUDC\";\n\n\t}\n}\n",
            },
            {
                "code": "// ***** We got them!! *****",
                "code_hint": "// ***** We got them!! *****",
                "default_code": "// ***** We got them!! *****",
            },
        ],
        [
            {
                "code": "# In how many days is the hack?\n# To find the solution, convert the given milliseconds\n# into days.\nmillis = 432000000\nseconds = millis / 1000\nminutes = seconds / 60\nhours = minutes / 60\ndays = hours / 24\nprint(days)\n",
                "code_hint": "#  In how many days is the hack?\n# To find the solution, convert the given milliseconds\n# into days.\nmillis = 432000000\nseconds = millis / \nminutes = seconds / \nhours = minutes / \ndays = hours / \nprint(days)\n",
                "default_code": "# In how many days is the hack?\n# To find the solution, convert the given milliseconds\n# into days.\nmillis = 432000000\n",
            },
            {
                "code": "# What is The Syndicate's bank account code?\n# To find the solution, find the sum of all\n# even numbers less than 12,386.\n\nnum = 12386;\nsum = 0;\ncount = 0;\nwhile (count < num):\n\tif (count % 2 == 0):\n\t\tsum += count;\n\tcount+=1;\nprint(sum);\n",
                "code_hint": "# What is The Syndicate's bank account code?\n# To find the solution, find the sum of all\n# even numbers less than 12,386.\n\nnum = 12386;\nsum = 0;\ncount = 0;\nwhile (count < num):\n\n\n\nprint(sum);\n",
                "default_code": "# What is The Syndicate's bank account code?\n# To find the solution, find the sum of all\n# even numbers less than 12,386.\n\nnum = 12386;\n",
            },
            {
                "code": "# The Syndicate is planning insider trading on an exchange in what city?\n# The message can be decoded by taking every\n# fifth letter of the document.\n\nnum = 5;\ninput = \"GIWTWVQMBEPDQUXCZWUHJWZKAKBSIVFZKDEZRFTXIPEZOCNFYUSJXTRHQFNXKMDMCUIAMOTPUWNGLSUTTQNRAZVOYCPCGMTCPMQSYOMAXBBIJSBWFAETBOCTIPVUXASJZUCOTIPZXCUXBRSMAQOLOTXGJTXBVUMTIQAZHFYZKEPKBCXYYSBCXYXFHBQLZIUMOICQXTUABRGLGFQFRODAYQXTWLUBONCPOITHFAWWRERPCZWDJTQRXTIODOKGRHFAZOOXQQBPTWTNXRDKVZAMFLADHTQUE\";\noutput = \"\"\nfor i in range(num - 1, len(input), num):\n\tif input[i] is 'X':\n\t\toutput += ' '\n\telse:\n\t\toutput += input[i]\nprint output\n",
                "code_hint": "# The Syndicate is planning insider trading on an exchange in what city?\n# The message can be decoded by taking every\n# fifth letter of the document.\n\nnum = 5;\ninput = \"GIWTWVQMBEPDQUXCZWUHJWZKAKBSIVFZKDEZRFTXIPEZOCNFYUSJXTRHQFNXKMDMCUIAMOTPUWNGLSUTTQNRAZVOYCPCGMTCPMQSYOMAXBBIJSBWFAETBOCTIPVUXASJZUCOTIPZXCUXBRSMAQOLOTXGJTXBVUMTIQAZHFYZKEPKBCXYYSBCXYXFHBQLZIUMOICQXTUABRGLGFQFRODAYQXTWLUBONCPOITHFAWWRERPCZWDJTQRXTIODOKGRHFAZOOXQQBPTWTNXRDKVZAMFLADHTQUE\";\noutput = \"\"\n\nprint output\n",
                "default_code": "# The Syndicate is planning insider trading on an exchange in what city?\n# The message can be decoded by taking every\n# fifth letter of the document.\n\nnum = 5;\ninput = \"GIWTWVQMBEPDQUXCZWUHJWZKAKBSIVFZKDEZRFTXIPEZOCNFYUSJXTRHQFNXKMDMCUIAMOTPUWNGLSUTTQNRAZVOYCPCGMTCPMQSYOMAXBBIJSBWFAETBOCTIPVUXASJZUCOTIPZXCUXBRSMAQOLOTXGJTXBVUMTIQAZHFYZKEPKBCXYYSBCXYXFHBQLZIUMOICQXTUABRGLGFQFRODAYQXTWLUBONCPOITHFAWWRERPCZWDJTQRXTIODOKGRHFAZOOXQQBPTWTNXRDKVZAMFLADHTQUE\";",
            },
            {
                "code": "# What is the financial publication The Syndicate is trying to hack?\n# To decode a 5-rail cipher like this, put the code in a matrix with a\n# length of 5 (5 rows). Then read the code from top to bottom, left to right\n\n\ncipherText = \"TLSHTIIIHA_AHNAMENTCEALE__OK_N_SPI__FCT.\"\nrows = 5\ncolumns = len(cipherText) / rows\nmatrix = [[0 for x in range(columns)] for y in range(rows)]\ntextIdx = 0\n\nfor row in range(0,len(matrix)):\n\tfor col in range(0, len(matrix[0])):\n\t\tif textIdx < len(cipherText):\n\t\t\tmatrix[row][col] = cipherText[textIdx]\n\t\telse:\n\t\t\tmatrix[row][col] = '-'\n\t\ttextIdx += 1\n\noutput = \"\"\n\nfor col in range(0, len(matrix[0])):\n\tfor row in range(0, len(matrix)):\n\t\toutput += matrix[row][col]\n\nprint output\n",
                "code_hint": "# What is the financial publication The Syndicate is trying to hack?\n# To decode a 5-rail cipher like this, put the code in a matrix with a\n# length of 5 (5 rows). Then read the code from top to bottom, left to right\n\n\ncipherText = \"TLSHTIIIHA_AHNAMENTCEALE__OK_N_SPI__FCT.\";\ncolumns = 5;\nrows = len(cipherText) / columns;\nmatrix = [[0 for x in range(columns)] for y in range(rows)]\ntextIdx = 0;\n\n# We have a matrix with 5 rows and 8 columns\n# Fill it with the cipherText from left to right\n# and top to bottom\n\n# Now read through the matrix down each column\n# from top to bottom and left to right and build a String\n# of the characters.\n",
                "default_code": "# What is the financial publication The Syndicate is trying to hack?\n# To decode a 5-rail cipher like this, put the code in a matrix with a\n# length of 5 (5 rows). Then read the code from top to bottom, left to right\n\n\ncipherText = \"TLSHTIIIHA_AHNAMENTCEALE__OK_N_SPI__FCT.\";\ncolumns = 5;\n",
            },
            {
                "code": "# To what country is the Kingpin planning to flee?\n# To find the solution, exclude all the letters in the\n# code that appear more than once.\n\ncode = \"FJPSCYWJQXHGOUYIFVGHTXCJUYZQMPKEOFRLBXGJVANQOHMKBPXUDC\"\noutput = \"\"\n\nfor i in range(0, len(code)):\n\tif code.find(code[i]) == code.rfind(code[i]):\n\t\toutput += code[i]\n\nprint output\n",
                "code_hint": "# To what country is the Kingpin planning to flee?\n# To find the solution, exclude all the letters in the\n# code that appear more than once.\n\ncode = \"FJPSCYWJQXHGOUYIFVGHTXCJUYZQMPKEOFRLBXGJVANQOHMKBPXUDC\"\noutput = \"\"\n\n# The .find() String method returns the first index of a character\n# in a String.\n# The .rfind() String method returns the last index of a character\n# in a String.\n",
                "default_code": "# To what country is the Kingpin planning to flee?\n# To find the solution, exclude all the letters in the\n# code that appear more than once.\n\ncode = \"FJPSCYWJQXHGOUYIFVGHTXCJUYZQMPKEOFRLBXGJVANQOHMKBPXUDC\"\noutput = \"\"\n\n",
            },
            {
                "code": "# ***** We got them!! *****",
                "code_hint": "# ***** We got them!! *****",
                "default_code": "# ***** We got them!! *****",
            },
        ],
        [
            {
                "code": "// In how many days is the hack?\n// To find the solution, convert the given milliseconds\n// into days.\n\nvar millis = 432000000;\nvar seconds = millis / 1000;\nvar minutes = seconds / 60;\nvar hours = minutes / 60;\nvar days = hours / 24;\nconsole.log(days);\n",
                "code_hint": "// In how many days is the hack?\n// To find the solution, convert the given milliseconds\n// into days.\n\nvar millis = 432000000;\nvar seconds = millis / ;\nvar minutes = seconds / ;\nvar hours = minutes / ;\nvar days = hours / ;\nconsole.log(days);\n",
                "default_code": "// In how many days is the hack?\n// To find the solution, convert the given milliseconds\n// into days.\n\nvar millis = 432000000;\n\nconsole.log();\n",
            },
            {
                "code": "// What is The Syndicate's bank account code?\n// To find the solution, find the sum of all\n// even numbers less than 12,386.\n\nvar num = 12386;\nvar sum = 0;\nvar count = 0;\nwhile (count < num) {\n\tif (count % 2 === 0) {\n\t\tsum += count;\n\t}\n\tcount++;\n}\nconsole.log(sum);\n",
                "code_hint": "// What is The Syndicate's bank account code?\n// To find the solution, find the sum of all\n// even numbers less than 12,386.\n\nvar num = 12386;\nvar sum = 0;\nvar count = 0;\n// Create a Loop to find each even number and add it to the sum\nconsole.log(sum);\n",
                "default_code": "// What is The Syndicate's bank account code?\n// To find the solution, find the sum of all\n// even numbers less than 12,386.\n\nvar num = 12386;\n\nconsole.log();\n",
            },
            {
                "code": "// The Syndicate is planning insider trading on an exchange in what city?\n// The message can be decoded by taking every\n// fifth letter of the document.\n\nvar num = 5;\nvar input = \"GIWTWVQMBEPDQUXCZWUHJWZKAKBSIVFZKDEZRFTXIPEZOCNFYUSJXTRHQFNXKMDMCUIAMOTPUWNGLSUTTQNRAZVOYCPCGMTCPMQSYOMAXBBIJSBWFAETBOCTIPVUXASJZUCOTIPZXCUXBRSMAQOLOTXGJTXBVUMTIQAZHFYZKEPKBCXYYSBCXYXFHBQLZIUMOICQXTUABRGLGFQFRODAYQXTWLUBONCPOITHFAWWRERPCZWDJTQRXTIODOKGRHFAZOOXQQBPTWTNXRDKVZAMFLADHTQUE\";\nvar output = \"\";\nfor (var i = num - 1; i < input.length; i += num) {\n\tif (input[i] == 'X') {\n\t\toutput += \" \";\n\t} else {\n\t\toutput += input[i];\n\t}\n}\nconsole.log(output);\n",
                "code_hint": "// The Syndicate is planning insider trading on an exchange in what city?\n// The message can be decoded by taking every\n// fifth letter of the document.\n\nvar num = 5;\nvar input = \"GIWTWVQMBEPDQUXCZWUHJWZKAKBSIVFZKDEZRFTXIPEZOCNFYUSJXTRHQFNXKMDMCUIAMOTPUWNGLSUTTQNRAZVOYCPCGMTCPMQSYOMAXBBIJSBWFAETBOCTIPVUXASJZUCOTIPZXCUXBRSMAQOLOTXGJTXBVUMTIQAZHFYZKEPKBCXYYSBCXYXFHBQLZIUMOICQXTUABRGLGFQFRODAYQXTWLUBONCPOITHFAWWRERPCZWDJTQRXTIODOKGRHFAZOOXQQBPTWTNXRDKVZAMFLADHTQUE\";\nvar output = \"\";\nfor (var i = num - 1; i < input.length; i += num) {\n\t// complete the for loop\n}\nconsole.log(output);\n",
                "default_code": "// The Syndicate is planning insider trading on an exchange in what city?\n// The message can be decoded by taking every\n// fifth letter of the document.\n\nvar input = \"GIWTWVQMBEPDQUXCZWUHJWZKAKBSIVFZKDEZRFTXIPEZOCNFYUSJXTRHQFNXKMDMCUIAMOTPUWNGLSUTTQNRAZVOYCPCGMTCPMQSYOMAXBBIJSBWFAETBOCTIPVUXASJZUCOTIPZXCUXBRSMAQOLOTXGJTXBVUMTIQAZHFYZKEPKBCXYYSBCXYXFHBQLZIUMOICQXTUABRGLGFQFRODAYQXTWLUBONCPOITHFAWWRERPCZWDJTQRXTIODOKGRHFAZOOXQQBPTWTNXRDKVZAMFLADHTQUE\";\n\nconsole.log();\n",
            },
            {
                "code": "// What is the financial publication The Syndicate is trying to hack?\n// To decode a 5-rail cipher like this, put the code in a matrix with a\n// length of 5 (5 rows). Then read the code from top to bottom, left to right\n\nvar cipherText = \"TLSHTIIIHA_AHNAMENTCEALE__OK_N_SPI__FCT.\";\nvar rows = 5;\nvar columns = cipherText.length / rows;\nvar matrix = [];\nfor (var i = 0; i < rows; i++) {\n\tmatrix[i] = [];\n}\nvar textIdx = 0;\nvar output = \"\";\n\nfor (var row = 0; row < rows; row++) {\n\tfor ( var col = 0; col < columns; col++) {\n\t\tif (textIdx < cipherText.length) {\n\t\t\tmatrix[row][col] = cipherText[textIdx];\n\t\t} else {\n\t\t\tmatrix[row][col] = '-';\n\t\t}\n\t\ttextIdx++;\n\t}\n}\n\nfor (var col = 0; col < matrix[0].length; col++) {\n\tfor (var row = 0; row < matrix.length; row++) {\n\t\toutput += matrix[row][col];\n\t}\n}\n\nconsole.log(output);\n",
                "code_hint": "// What is the financial publication The Syndicate is trying to hack?\n// To decode a 5-rail cipher like this, put the code in a matrix with a\n// length of 5 (5 rows). Then read the code from top to bottom, left to right\n\nvar cipherText = \"TLSHTIIIHA_AHNAMENTCEALE__OK_N_SPI__FCT.\";\nvar rows = 5;\nvar columns = cipherText.length / rows;\nvar matrix = [];\nfor (var i = 0; i < rows; i++) {\n\tmatrix[i] = [];\n}\nvar textIdx = 0;\nvar output = \"\";\n\n// We have a matrix with 5 rows and 8 columns\n// Fill it with the cipherText from left to right\n// and top to bottom\n\n// Now read through the matrix down each column\n// from top to bottom and left to right and build a String\n// of the characters.\n\nconsole.log(output);\n",
                "default_code": "// What is the financial publication The Syndicate is trying to hack?\n// To decode a 5-rail cipher like this, put the code in a matrix with a\n// length of 5 (5 rows). Then read the code from top to bottom, left to right\n\nvar cipherText = \"TLSHTIIIHA_AHNAMENTCEALE__OK_N_SPI__FCT.\";\n\nconsole.log();\n",
            },
            {
                "code": "// To what country is the Kingpin planning to flee?\n// To find the solution, exclude all the letters in the\n// code that appear more than once.\n\nvar code = \"FJPSCYWJQXHGOUYIFVGHTXCJUYZQMPKEOFRLBXGJVANQOHMKBPXUDC\";\nvar output = \"\";\n\nfor (var i = 0; i < code.length; i++){\n\tif( code.indexOf(code[i]) == code.lastIndexOf(code[i]) ) {\n\t\toutput += code[i];\n\t}\n}\n\nconsole.log(output);\n",
                "code_hint": "// To what country is the Kingpin planning to flee?\n// To find the solution, exclude all the letters in the\n// code that appear more than once.\n\nvar code = \"FJPSCYWJQXHGOUYIFVGHTXCJUYZQMPKEOFRLBXGJVANQOHMKBPXUDC\";\nvar output = \"\";\n\n// The .indexOf() String method returns the first index of a character\n// in a String.\n// The .lastIndexOf() String method returns the last index of a character\n// in a String.\n\nconsole.log(output);\n",
                "default_code": "// To what country is the Kingpin planning to flee?\n// To find the solution, exclude all the letters in the\n// code that appear more than once.\n\nvar code = \"FJPSCYWJQXHGOUYIFVGHTXCJUYZQMPKEOFRLBXGJVANQOHMKBPXUDC\";\n\nconsole.log();\n",
            },
            {
                "code": "// ***** We got them!! *****",
                "code_hint": "// ***** We got them!! *****",
                "default_code": "// ***** We got them!! *****",
            },
        ]
    ],
    userSubmitted: ''
};
export default function (state = initialState, action) {
    switch (action.type) {
        case 'UPDATE_CODE':
            return {
                ...state,
                userSubmitted: action.newCode,
            };
        default:
            return state;
    }
}